### ISSUE TITLE
How to install via community?

### ISSUE THREAD

**Issue by swuphoto** [sytone/obsidian-queryallthethings#1]
Looked at the document (BTW it's a broken link) and trying to search "query all things", nothing.

**Comment by sytone** [comment]
The plugin is still pending acceptance in the plugin community. 

Which document has the broken link as I had thought I had fixed them all.

**Comment by sytone** [comment]
Found the issue, fixing it in my commit shortly.

**Comment by swuphoto** [comment]
I only tried the link in the Getting Started session.

**Comment by sytone** [comment]
The link is now fixed and pointing to the wiki. Still waiting for community approval. Closing up as link is resolved.
