### ISSUE TITLE
Special characters in file name cause broken links

### ISSUE THREAD

**Issue by reff** [sytone/obsidian-queryallthethings#15]
The following snippet works fine until a note **file name** contains a special symbol like `'`

```qatt
query: |
  SELECT ALL basename
  FROM obsidian_markdown_notes
  LIMIT 20
template: |
  {{#each result}}
  <small>[[{{basename}}]]</small>
  {{/each}}
```

Special characters cause something like this `&#x27;` inside the resulting link. Thus, the link becomes broken.

A big deal, one might think. But different languages might require one of those characters.

**Comment by sytone** [comment]
Wrap basename in three braces like this. {{{basename}}}

This will let handlebars the rending engine know not to html escape the content and trusts that you have already handled any escaping already.


This will cause the single quote to render correctly.

Let me know how it goes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Andrew Reva ***@***.***>
Sent: Sunday, March 31, 2024 12:26:39 PM
To: sytone/obsidian-queryallthethings ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sytone/obsidian-queryallthethings] Special characters in file name cause broken links (Issue #15)


The following snippet works fine until a note file name contains a special symbol like '

query: |
  SELECT ALL basename
  FROM obsidian_markdown_notes
  LIMIT 20
template: |
  {{#each result}}
  <small>[[{{basename}}]]</small>
  {{/each}}


Special characters cause something like this &#x27; inside the resulting link. Thus, the link becomes broken.

A big deal, one might think. But different languages might require one of those characters.

**Comment by reff** [comment]
Many thanks for your prompt reply. It works like a charm with the triple-mustache embracement.
And the plugin is really great (my updated dashboard page is now powered by QATT). Thank you
