### ISSUE TITLE
Dataview errors pervent building qatt cache

### ISSUE THREAD

**Issue by gentzeng** [sytone/obsidian-queryallthethings#28]
**Describe the bug**
qatt blocks do not render. It seems that dataview interferes the qatt cache building. Tested with Version 1.1.1 to 1.1.3

**To Reproduce**
1. Open obsidian
2. open dev console
3. see error -> screenshots

**Expected behavior**
qatt blocks render

**Screenshots**
![Dataview refresh error 2024-10-02 15-11-31 +0200](https://github.com/user-attachments/assets/11622057-b05e-4f63-b0af-d892ad6aa780)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Obsidian Version: v1.6.7
 - Plugin Version: 1.0.2

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android
 - Obsidian Version: v1.6.7
 - Plugin Version: 1.0.2

**Comment by sytone** [comment]
I validated the new build with a clean vault. However dataview was not enabled. I do not have it enabled on my vault either. 

I am remote at the moment but if dataview is disabled does the error still happen?

I am considering removing the dataview integration as I do not have larger coverage for it and I no longer use it.

**Comment by gentzeng** [comment]
Thanks for your fast replies!

I made a video of a test vault:

https://github.com/user-attachments/assets/15afbd75-e783-4a3e-8051-077fe83fe48d

**Comment by sytone** [comment]
I just enabled Dataview on my main vault and things defiantly broke in the settings but no exceptions. I also completely removed it as well as tried it with it installed but disabled and did not see the exceptions you are seeing. Will make a vault shortly to see if I can reproduce.

**Comment by sytone** [comment]
Ok, I did the following. 

- Created a new vault using Obsidian 1.6.7
- Enabled plugins
- Created a set of pages 
- Installed QATT
- Restarted Obsidian so I had a clean slate
- Added the below code block to the Welcome page
- Rendered without any errors in log
- Installed Dataview 
- Restarted Obsidian so I had a clean slate
- Went to welcome pages and it rendered the block with no errors. 
- Enabled Dataview
- Restarted Obsidian so I had a clean slate
- Went to welcome pages and it rendered the block with no errors. 

Query:
```qatt
query: |
  SELECT * FROM obsidian_notes
template: |
  {{#each result}}
    - {{basename}}
  {{/each}}
```

I am not sure where these exceptions are coming from. Can you share your data.json in the plugins folder so I can see the settings being used for qatt? There may be something different there? Please ensure you remove and personal information before posting it.

**Comment by gentzeng** [comment]
My testvault, that one of the last video, has qatt-1.1.3.
data.json looks like this:
```
{
  "onStartSqlQueries": "CREATE TABLE my_lookup(name,birthday);\nINSERT INTO my_lookup VALUES (\"fred\", 2000-02-03);",
  "announceUpdates": false,
  "version": "",
  "mainHeadingOpen": true,
  "generalHeadingOpen": true,
  "internalLoggingConsoleLogLimit": 10,
  "disableDataviewMissingNotification": false,
  "disableCustomJsMissingNotification": false,
  "enableEditorRightClickMenu": true
}
```

The settings page of qatt does not have a decounce option. Do i have to manually add that?
![qatt 1 1 3 settings 2024-10-02 22-53-39 +0200](https://github.com/user-attachments/assets/657bd510-451a-4dea-87d2-de998e6642b5)

**Comment by sytone** [comment]
No, it is missing settings. I saw this when dataview was on. When it was off all settings were showing but I did not see an exception with the creation of settings so that was on the backlog and assumed it was just me.

If you toggle one of the settings and then close and open it do you still just see this limited set?

**Comment by gentzeng** [comment]
No, the set of settings still is the same

**Comment by gentzeng** [comment]
I don't know why but it currently works. No errors in the console and the debouncing works perfectly. Also, all the settings are now visible :shrug:

**Comment by sytone** [comment]
Ok. So there is something weird with one of the internal services. I'm going to try and remove dataview to see if it happens again. Process of elimination to track this one down.

**Comment by sytone** [comment]
Have a change that will remove dataview, need to somehow work out impact. Ill add this to roadmap in project plan.
