### ISSUE TITLE
Broken Project link in README

### ISSUE THREAD

**Issue by darthwalsh** [sytone/obsidian-queryallthethings#29]
**Describe the bug**
In [README.md](https://github.com/sytone/obsidian-queryallthethings/blob/main/README.md#roadmap-and-issues), this link 404's for me:

> Look at the [Qatt Project](https://github.com/users/sytone/projects/4) 

**Expected behavior**
Not sure what the link is supposed to be, in one of these?

- https://github.com/sytone/obsidian-queryallthethings/projects
- https://github.com/sytone?tab=projects

Both these look empty to me, but maybe the Project isn't set to public visibility:

**Additional context**
Your plugin looks cool :)

**Comment by sytone** [comment]
Fixed visibility, thanks for reporting it and thinking the plugin looks cool! :)
